import argparse
import logging
import os
import sys
from typing import Any, Dict, List, Optional, Tuple, Union

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr, validate_call
from typing_extensions import Annotated

from worldnewsapi.api_client import ApiClient, RequestSerialized
from worldnewsapi.configuration import Configuration
from worldnewsapi.models.top_news200_response import TopNews200Response
from worldnewsapi.models.search_news200_response import SearchNews200Response

logger = logging.getLogger(__name__)


class NewsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def top_news(
        self,
        source_country: Annotated[
            str,
            Field(
                strict=True,
                max_length=2,
                description="The ISO 3166 country code of the country for which top news should be retrieved.",
            ),
        ],
        language: Annotated[
            str,
            Field(
                strict=True,
                max_length=2,
                description="The ISO 6391 language code of the top news. The language must be one spoken in the source-country.",
            ),
        ],
        var_date: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=10)]],
            Field(
                description="The date for which the top news should be retrieved. If no date is given, the current day is assumed."
            ),
        ] = None,
        headlines_only: Annotated[
            Optional[StrictBool],
            Field(
                description="Whether to only return basic information such as id, title, and url of the news."
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TopNews200Response:
        """Top News

        Get the top news from a country in a language for a specific date. The top news are clustered from multiple sources in the given country. The more news in a cluster the higher the cluster is ranked.

        :param source_country: The ISO 3166 country code of the country for which top news should be retrieved. (required)
        :type source_country: str
        :param language: The ISO 6391 language code of the top news. The language must be one spoken in the source-country. (required)
        :type language: str
        :param var_date: The date for which the top news should be retrieved. If no date is given, the current day is assumed.
        :type var_date: str
        :param headlines_only: Whether to only return basic information such as id, title, and url of the news.
        :type headlines_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._top_news_serialize(
            source_country=source_country,
            language=language,
            var_date=var_date,
            headlines_only=headlines_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        logger.debug(
            "top_news — requête: source_country=%s language=%s var_date=%s headlines_only=%s",
            source_country,
            language,
            var_date,
            headlines_only,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "TopNews200Response",
            "401": None,
            "402": None,
            "403": None,
            "404": None,
            "406": None,
            "429": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        result: TopNews200Response = self.api_client.response_deserialize(  # type: ignore[assignment]
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data
        logger.debug(
            "top_news — réponse: %d clusters reçus",
            len(result.top_news) if result.top_news else 0,
        )
        return result

    def _top_news_serialize(
        self,
        source_country,
        language,
        var_date,
        headlines_only,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None
        _collection_formats: Dict[str, str] = {}
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        if source_country is not None:
            _query_params.append(("source-country", source_country))

        if language is not None:
            _query_params.append(("language", language))

        if var_date is not None:
            _query_params.append(("date", var_date))

        if headlines_only is not None:
            _query_params.append(("headlines-only", headlines_only))

        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["application/json"]
            )

        _auth_settings: List[str] = ["apiKey", "headerApiKey"]

        logger.debug("top_news — query_params: %s", _query_params)

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/top-news",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def search_news(
        self,
        text: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=100)]],
            Field(description="The text to match in the news content (min 3 chars)."),
        ] = None,
        text_match_indexes: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=100)]],
            Field(
                description="Where to search: title, content, or both (comma-separated)."
            ),
        ] = None,
        source_country: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=2)]],
            Field(description="ISO 3166 country code of the news origin."),
        ] = None,
        language: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=2)]],
            Field(description="ISO 6391 language code of the news."),
        ] = None,
        min_sentiment: Annotated[
            Optional[
                Union[
                    Annotated[float, Field(le=1, strict=True, ge=-1)],
                    Annotated[int, Field(le=1, strict=True, ge=-1)],
                ]
            ],
            Field(description="Minimal sentiment in range [-1,1]."),
        ] = None,
        max_sentiment: Annotated[
            Optional[
                Union[
                    Annotated[float, Field(le=1, strict=True, ge=-1)],
                    Annotated[int, Field(le=1, strict=True, ge=-1)],
                ]
            ],
            Field(description="Maximal sentiment in range [-1,1]."),
        ] = None,
        earliest_publish_date: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=19)]],
            Field(
                description="News must have been published after this date (YYYY-MM-DD HH:MM:SS)."
            ),
        ] = None,
        latest_publish_date: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=19)]],
            Field(
                description="News must have been published before this date (YYYY-MM-DD HH:MM:SS)."
            ),
        ] = None,
        news_sources: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=10000)]],
            Field(description="Comma-separated list of news sources."),
        ] = None,
        authors: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=300)]],
            Field(description="Comma-separated list of author names."),
        ] = None,
        categories: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=300)]],
            Field(
                description="Comma-separated list of categories (e.g. politics,technology)."
            ),
        ] = None,
        entities: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=10000)]],
            Field(description="Filter news by entities."),
        ] = None,
        location_filter: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=100)]],
            Field(description='Filter by radius: "lat,lon,radius_km".'),
        ] = None,
        sort: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=100)]],
            Field(description="Sorting criteria (publish-time)."),
        ] = None,
        sort_direction: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=4)]],
            Field(description="ASC or DESC."),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=10000, strict=True, ge=0)]],
            Field(description="Number of news to skip [0,100000]."),
        ] = None,
        number: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="Number of news to return [1,100]."),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SearchNews200Response:
        """Search News

        Search and filter news by text, date, location, category, language, and more.

        :param text: Text to search for (min 3 chars, max 100 chars).
        :param language: ISO 639-1 language code.
        :param number: Number of results to return [1,100].
        :param sort: Sort criteria (publish-time).
        :param sort_direction: ASC or DESC.
        :return: SearchNews200Response
        """
        logger.debug(
            "search_news — requête: text=%s language=%s number=%s",
            text,
            language,
            number,
        )
        _param = self._search_news_serialize(
            text=text,
            text_match_indexes=text_match_indexes,
            source_country=source_country,
            language=language,
            min_sentiment=min_sentiment,
            max_sentiment=max_sentiment,
            earliest_publish_date=earliest_publish_date,
            latest_publish_date=latest_publish_date,
            news_sources=news_sources,
            authors=authors,
            categories=categories,
            entities=entities,
            location_filter=location_filter,
            sort=sort,
            sort_direction=sort_direction,
            offset=offset,
            number=number,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "SearchNews200Response",
            "401": None,
            "402": None,
            "403": None,
            "404": None,
            "406": None,
            "429": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        result: SearchNews200Response = self.api_client.response_deserialize(  # type: ignore[assignment]
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data
        logger.debug(
            "search_news — réponse: %d articles reçus",
            len(result.news) if result.news else 0,
        )
        return result

    def _search_news_serialize(
        self,
        text,
        text_match_indexes,
        source_country,
        language,
        min_sentiment,
        max_sentiment,
        earliest_publish_date,
        latest_publish_date,
        news_sources,
        authors,
        categories,
        entities,
        location_filter,
        sort,
        sort_direction,
        offset,
        number,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None
        _collection_formats: Dict[str, str] = {}
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        if text is not None:
            _query_params.append(("text", text))
        if text_match_indexes is not None:
            _query_params.append(("text-match-indexes", text_match_indexes))
        if source_country is not None:
            _query_params.append(("source-country", source_country))
        if language is not None:
            _query_params.append(("language", language))
        if min_sentiment is not None:
            _query_params.append(("min-sentiment", min_sentiment))
        if max_sentiment is not None:
            _query_params.append(("max-sentiment", max_sentiment))
        if earliest_publish_date is not None:
            _query_params.append(("earliest-publish-date", earliest_publish_date))
        if latest_publish_date is not None:
            _query_params.append(("latest-publish-date", latest_publish_date))
        if news_sources is not None:
            _query_params.append(("news-sources", news_sources))
        if authors is not None:
            _query_params.append(("authors", authors))
        if categories is not None:
            _query_params.append(("categories", categories))
        if entities is not None:
            _query_params.append(("entities", entities))
        if location_filter is not None:
            _query_params.append(("location-filter", location_filter))
        if sort is not None:
            _query_params.append(("sort", sort))
        if sort_direction is not None:
            _query_params.append(("sort-direction", sort_direction))
        if offset is not None:
            _query_params.append(("offset", offset))
        if number is not None:
            _query_params.append(("number", number))

        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["application/json"]
            )

        _auth_settings: List[str] = ["apiKey", "headerApiKey"]

        logger.debug("_search_news_serialize — query_params: %s", _query_params)

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/search-news",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )


def get_news_api() -> "NewsApi":
    """Retourne une instance NewsApi configurée.

    En développement (``WORLDNEWS_MOCK=True``), retourne un wrapper qui
    intercepte les appels et renvoie des données fixes — évite d'atteindre
    le rate-limit de 50 points/jour de l'API gratuite.

    En production (``ENVIRONMENT=production``), appelle l'API réelle.
    """
    from core.config import WORLDNEWS_MOCK, WORLDNEWSAPI_KEY  # noqa: PLC0415

    if WORLDNEWS_MOCK:
        logger.info("get_news_api — mode MOCK activé (ENVIRONMENT != production)")
        return _MockNewsApi()  # type: ignore[return-value]

    logger.debug("get_news_api — mode RÉEL (clé présente: %s)", bool(WORLDNEWSAPI_KEY))
    configuration = Configuration(host="https://api.worldnewsapi.com")
    configuration.api_key["apiKey"] = WORLDNEWSAPI_KEY
    configuration.api_key["headerApiKey"] = WORLDNEWSAPI_KEY
    api_client = ApiClient(configuration)
    return NewsApi(api_client)


class _MockNewsApi:
    """Implémentation factice de NewsApi pour le développement local.

    Respecte la même interface que ``NewsApi`` (duck typing) afin d'être
    interchangeable sans modifier les consommateurs.
    """

    def top_news(
        self,
        source_country: str = "fr",
        language: str = "fr",
        var_date: Optional[str] = None,
        **kwargs,
    ) -> "TopNews200Response":
        from core.worldnewsapi.mock_data import make_top_news_mock

        effective_date = var_date or __import__("datetime").date.today().isoformat()
        logger.debug("_MockNewsApi.top_news — date=%s", effective_date)
        return make_top_news_mock(date=effective_date)

    def search_news(
        self,
        text: Optional[str] = None,
        language: Optional[str] = None,
        number: Optional[int] = None,
        **kwargs,
    ) -> "SearchNews200Response":
        from core.worldnewsapi.mock_data import make_search_news_mock

        logger.debug("_MockNewsApi.search_news — query=%s", text)
        return make_search_news_mock(query=text or "")


def main() -> None:
    """Point d'entrée standalone — utilisable pour smoke-test CI/CD.

    Usage:
        uv run python src/core/worldnewsapi/worldnews.py [--country fr] [--lang fr] [--debug]

    Codes de sortie:
        0  succès
        1  erreur (API inaccessible, clé invalide, etc.)
        2  clé WORLDNEWSAPI_KEY absente
    """
    parser = argparse.ArgumentParser(description="Smoke-test WorldNewsAPI — top_news")
    parser.add_argument(
        "--country", default="fr", help="Code ISO 3166 pays (défaut: fr)"
    )
    parser.add_argument(
        "--lang", default="fr", help="Code ISO 639-1 langue (défaut: fr)"
    )
    parser.add_argument(
        "--date", default=None, help="Date YYYY-MM-DD (défaut: aujourd'hui)"
    )
    parser.add_argument(
        "--headlines-only", action="store_true", help="Titres uniquement"
    )
    parser.add_argument("--debug", action="store_true", help="Active les logs DEBUG")
    args = parser.parse_args()

    log_level = logging.DEBUG if args.debug else logging.INFO
    logging.basicConfig(
        level=log_level,
        format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
        stream=sys.stderr,
    )

    # Résolution du chemin src/ pour les imports relatifs au mode standalone
    src_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if src_dir not in sys.path:
        sys.path.insert(0, src_dir)

    from core.config import WORLDNEWSAPI_KEY  # noqa: PLC0415

    if not WORLDNEWSAPI_KEY:
        logger.error("WORLDNEWSAPI_KEY absent du .env — impossible d'appeler l'API.")
        sys.exit(2)

    logger.info(
        "Smoke-test top_news: country=%s lang=%s date=%s headlines_only=%s",
        args.country,
        args.lang,
        args.date,
        args.headlines_only,
    )

    try:
        api = get_news_api()
        result = api.top_news(
            source_country=args.country,
            language=args.lang,
            var_date=args.date,
            headlines_only=args.headlines_only or None,
        )
    except Exception:
        logger.exception("Échec de l'appel à top_news")
        sys.exit(1)

    total_clusters = len(result.top_news) if result.top_news else 0
    total_articles = (
        sum(len(c.news or []) for c in result.top_news) if result.top_news else 0
    )

    logger.info("OK — %d clusters, %d articles reçus.", total_clusters, total_articles)

    if total_clusters == 0:
        logger.warning("Aucun cluster retourné — vérifier la clé ou les paramètres.")
        sys.exit(1)

    # Affiche le premier titre pour confirmation visuelle
    if result.top_news:
        first_cluster = result.top_news[0]
        first_article = first_cluster.news[0] if first_cluster.news else None
        if first_article:
            logger.info(
                "Premier article: [%s] %s", first_article.id, first_article.title
            )

    sys.exit(0)


if __name__ == "__main__":
    main()
